/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencadc_erfa_ERFALib */

#ifndef _Included_org_opencadc_erfa_ERFALib
#define _Included_org_opencadc_erfa_ERFALib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencadc_erfa_ERFALib
 * Method:    tai2tt
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_opencadc_erfa_ERFALib_tai2tt
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_opencadc_erfa_ERFALib
 * Method:    tt2tai
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_opencadc_erfa_ERFALib_tt2tai
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
